/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.test;

import org.junit.jupiter.api.Test;
import algorithm.test.baekjoon.Main;

class AppTest {
  @Test
  void appHasAGreeting() {
    Main classUnderTest = new Main();
  }
}
